version: '3'

services:
  chimucheck-web:
    container_name: chimucheck-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
    volumes:
      - ./public/avatars:/app/public/avatars
      - ./public/avatars:/app/.next/standalone/public/avatars
      - ./public/uploads:/app/public/uploads
      - ./public/uploads:/app/.next/standalone/public/uploads
      - ./data:/app/data
